Complete step 1
glasss13/learnsomething pull request #2
Opened 2023-11-02 05:14 UTC by glasss13

1. What is the purpose of this PR?
Finish step 1
2. What changes did you make? Why?
I implemented the methods for the `PricingUtil` class and added tests.
3 .What bugs did you find while testing?
I had to implement an empty constructor for the python code to be able to run the constructor.

**This PR Specific:**

1. What challenges did you face while writing the module from scratch?
None
2. How did you ensure your unit tests are comprehensive?
I made sure to include various combinations of different important values for the three inputs to `calcVal`.
3. Did you have enough guidance to complete the task?
It was a little bit ambiguous as to whether `val` should be updated, but I assumed it was.

2023-11-02 23:24 UTC, minnce requested changes

2023-11-02 23:24 UTC, minnce commented on src/pricingutil.cpp
> +PricingUtil::PricingUtil() {}
initialize val here please

2023-11-03 00:32 UTC, glasss13 commented on src/pricingutil.cpp
> +PricingUtil::PricingUtil() {}
Done.

2023-11-03 00:39 UTC, minnce approved these changes
Thanks for making that change! LGTM :)

2023-11-03 00:45 UTC, glasss13 commented
> Thanks for making that change! LGTM :)

No problem! Thanks.

2023-11-03 00:45 UTC, merged